CREATE DATABASE IF NOT EXISTS TENTHGEAR;
SHOW DATABASES;
USE TENTHGEAR; # CONNECTING TO THE NEWLY CREATED DATABASE
SHOW TABLES; # TO SHOW ALL THE TABLES IN THE DATABASE

DROP TABLE  IF EXISTS VEHICLES,CUSTOMERS, VENDORS, EXPENSES;

CREATE TABLE VENDORS
(
  ID  INT(11) NOT NULL  AUTO_INCREMENT primary key,
  VENDORSNAME VARCHAR(60) NOT NULL
);

CREATE TABLE VEHICLES
(
  ID INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VNDRID INT(11) NOT NULL,
  image mediumblob,
  YEAR VARCHAR(4),
  MAKE VARCHAR(50),
  MODEL VARCHAR(50),
  MILES INT (8),
  VIN VARCHAR(18),
  COLOR VARCHAR(20),
  PLATE VARCHAR(15),
  COST DECIMAL(6,2),
  CONSTRAINT FOREIGN KEY FK_VDRID (VNDRID) REFERENCES VENDORS(ID)
);

CREATE TABLE CUSTOMERS
(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  vid int (11) not null,
  FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
  MIDDLENAME varchar(1),
  streetnum varchar(9),
  streetadd varchar(60),
  city varchar(20),
  state varchar(2),
  zip int(5) ,
  FOREIGN KEY fk_vid (vid) REFERENCES VEHICLES(ID)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);

CREATE TABLE EXPENSES
(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VNDRID INT(11) NOT NULL,
  COMMENT VARCHAR(255),
  COST DECIMAL (5,2),
  DATE DATETIME ,
  VEHICLEID INT (11),
  CONSTRAINT FOREIGN KEY fk_exvid (VEHICLEID) REFERENCES VEHICLES (ID),
  CONSTRAINT FOREIGN KEY FK_VDRID2 (VNDRID) REFERENCES VENDORS(ID)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);

SHOW TABLES;
